Média de Avaliações de Jogos Eletrônicos Usando Numpy


Você é um analista de dados em uma empresa de jogos eletrônicos e recebeu uma tarefa para analisar as notas de avaliação de jogos de um banco de dados. As notas de avaliação são armazenadas em um array numpy, uma biblioteca do Python que permite trabalhar com matrizes multidimensionais e oferece diversas funções e operações matemáticas. Uma das vantagens do numpy em relação às listas é que as operações em arrays são mais eficientes computacionalmente, permitindo lidar com grandes quantidades de dados de forma mais rápida. Você precisa calcular a média das notas para ter uma ideia da satisfação dos jogadores com os jogos. Para isso, você vai criar uma função chamada media_avaliacao, que recebe como argumento um array do tipo numpy e retorna um único valor float com a média.

In [1]:
import numpy as np

def media_avaliacao(arr: np.ndarray) -> float:
	array = np.array(arr)
	return array.mean()

Cálculo da soma dos elementos de cada coluna em uma matriz usando NumPy

O processamento digital de imagens é uma área que utiliza técnicas computacionais para processar e analisar imagens digitais. Uma das bibliotecas utilizadas nessa área é o NumPy, uma biblioteca Python que permite trabalhar com matrizes multidimensionais e oferece diversas funções e operações matemáticas.

Suponha que você seja um desenvolvedor de software de processamento digital de imagens e foi designado para criar uma função que calcule a soma dos elementos de cada coluna de uma matriz de entrada. A matriz de entrada pode ter qualquer tamanho e é armazenada como um array NumPy.

Assinatura da função: soma_colunas(matriz: np.ndarray) -> np.ndarray

In [8]:
import numpy as np
def soma_colunas(matriz: np.ndarray) -> np.ndarray:
	soma = np.sum(matriz, axis=0)
	return soma
			

In [9]:
soma_colunas([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

array([12, 15, 18])

In [ ]:
''' matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

soma = soma_colunas(matriz)

>>> array([12, 15, 18])'''

Análise de transações financeiras com NumPy

A biblioteca NumPy é uma ferramenta amplamente utilizada na área financeira para a análise de grandes conjuntos de dados, principalmente na detecção de fraudes bancárias. Como analista de dados de uma instituição financeira, você foi designado para analisar transações financeiras a fim de identificar possíveis fraudes. A instituição coleta os dados das transações realizadas e armazena-os em arrays NumPy. Escreva uma função chamada analisa_transacoes, que recebe como entrada um array NumPy de valores de transações e retorna um array NumPy do tipo float64 com as seguintes medidas estatísticas:

Média;
Desvio padrão;
Valor mínimo;
Valor máximo;
Mediana;
Quartis 25% e 75%.

Com essas medidas estatísticas, a instituição poderá identificar possíveis padrões e anomalias nos dados das transações, que podem ser sinais de atividades fraudulentas.

Dica: Utilize as funções disponíveis no NumPy para calcular cada medida estatística.

In [22]:
def analisa_transacoes(arr: np.ndarray) -> np.ndarray:
	lista = np.array([np.mean(arr), np.std(arr), np.min(arr), np.max(arr), np.median(arr), np.quantile(arr, 0.25), np.quantile(arr, 0.75)])
	return lista
	

In [23]:
analisa_transacoes(np.array([100.0, 200.0, 50.0, 300.0, 250.0, 120.0, 80.0, 500.0]))

array([200.        , 139.55285737,  50.        , 500.        ,
       160.        ,  95.        , 262.5       ])

Concatenação de Arrays Numpy para Análise de Vendas em Diferentes Regiões

Você é um analista de dados em uma empresa de vendas online e recebeu uma tarefa para analisar as vendas de um determinado produto em diferentes regiões do país. As informações de vendas são armazenadas em dois arrays numpy, um com as vendas da região Sul e outro com as vendas da região Norte. O numpy é uma biblioteca do Python utilizada para trabalhar com matrizes e arrays multidimensionais de forma eficiente, que oferece diversas funções e operações para facilitar a manipulação desses objetos. Uma das vantagens do numpy em relação às listas do Python é a velocidade e eficiência nas operações com arrays. Você precisa concatenar os dois arrays para ter uma visão geral das vendas do produto em todo o país. Para isso, você vai criar uma função chamada concatena_array, que recebe como argumentos dois arrays do tipo numpy e retorna um único array do tipo numpy concatenando os dois.

In [28]:
def concatena_array(arr1: np.ndarray, arr2: np.ndarray) -> np.ndarray:
	return np.concatenate((arr1, arr2))

In [29]:
vendas_sul = np.array([100, 150, 200])
vendas_norte = np.array([50, 75, 100])

concatena_array(vendas_sul, vendas_norte)

array([100, 150, 200,  50,  75, 100])

Cálculo do Índice de Massa Corporal (IMC) em um Dataframe

Você é um nutricionista e precisa criar uma ferramenta para calcular o Índice de Massa Corporal (IMC) de seus pacientes. Para isso, você pode utilizar a biblioteca Pandas do Python. Ela é uma biblioteca Python de código aberto que fornece ferramentas de análise e manipulação de dados de forma rápida e eficiente. O Pandas permite trabalhar com dados em formato de tabela, chamados de DataFrames, com colunas de tipos diferentes, além de oferecer funcionalidades para indexação, agregação, seleção, filtragem e visualização dos dados. Com essa biblioteca, é possível realizar tarefas de limpeza, transformação e modelagem de dados, sendo uma ferramenta muito útil em áreas como ciência de dados, finanças, economia, entre outras.

Escreva uma função chamada calcula_imc que receba um DataFrame pandas contendo as informações de nome, idade, sexo, altura e peso de um paciente, calcule o IMC e adicione uma nova coluna no DataFrame contendo o resultado do cálculo. Em seguida, a função deve retornar o DataFrame modificado.

A fórmula para calcular o IMC:\
IMC = peso / altura²

In [34]:
import pandas as pd

def calcula_imc(df: pd.DataFrame) -> pd.DataFrame:
	df['IMC'] = df['Peso'] / df['Altura'] **2
	print(df)

In [37]:
dados = {
    "Nome": ["João", "Maria", "José", "Ana", "Carlos"],
    "Idade": [30, 25, 40, 35, 28],
    "Sexo": ["M", "F", "M", "F", "M"],
    "Altura": [1.75, 1.68, 1.80, 1.65, 1.72],
    "Peso": [70, 55, 85, 75, 80]
}
df = pd.DataFrame(dados)
calcula_imc(df)


     Nome  Idade Sexo  Altura  Peso        IMC
0    João     30    M    1.75    70  22.857143
1   Maria     25    F    1.68    55  19.486961
2    José     40    M    1.80    85  26.234568
3     Ana     35    F    1.65    75  27.548209
4  Carlos     28    M    1.72    80  27.041644


Criação de uma Matriz Identidade Usando NumPy

No processamento digital de imagens, é comum utilizar matrizes para representar imagens e aplicar operações matemáticas sobre elas. Uma operação comum é a multiplicação de uma matriz por um escalar, que pode ser usado para ajustar o brilho ou a intensidade de cores de uma imagem. O NumPy é uma biblioteca do Python que permite trabalhar com matrizes multidimensionais e oferece diversas funções e operações matemáticas.

Nesse contexto, crie uma função chamada cria_matriz_identidade que receba dois parâmetros: o tamanho da matriz (n) e o fator de multiplicação (m). A função deve retornar uma matriz identidade de tamanho n x n multiplicada pelo fator m, representada como um array numpy.

In [42]:
import numpy as np
def cria_matriz_identidade(n:int, m:float) -> np.ndarray:
	matriz = np.identity((n))
	return matriz * m

In [43]:
cria_matriz_identidade(3, 2)

'''>>> array([[2., 0., 0.],
           [0., 2., 0.],
           [0., 0., 2.]])'''

'>>> array([[2., 0., 0.],\n           [0., 2., 0.],\n           [0., 0., 2.]])'

Criação de DataFrame Pandas para Apoio a Planejamento de Dieta

Suponha que você esteja desenvolvendo um sistema para apoio a planejamento de dieta, que tem como objetivo auxiliar as pessoas a atingirem seus objetivos de saúde por meio de uma alimentação equilibrada. Uma das funcionalidades desse sistema é o registro das informações pessoais dos usuários, tais como nome, idade, sexo, altura e peso.

Para armazenar essas informações, você pode utilizar a biblioteca pandas do Python, que permite trabalhar com tabelas de dados (DataFrames). Pandas é uma biblioteca Python de código aberto que fornece ferramentas de análise e manipulação de dados de forma rápida e eficiente. O Pandas permite trabalhar com dados em formato de tabela, chamados de DataFrames, com colunas de tipos diferentes, além de oferecer funcionalidades para indexação, agregação, seleção, filtragem e visualização dos dados. Com essa biblioteca, é possível realizar tarefas de limpeza, transformação e modelagem de dados, sendo uma ferramenta muito útil em áreas como ciência de dados, finanças, economia, entre outras.

Crie uma função chamada cria_dataframe que receba uma lista contendo as informações de nome, idade, sexo, altura e peso de 
n
n pessoas e retorne um DataFrame com essas informações.

In [48]:
import pandas as pd

def cria_dataframe(lista: list) -> pd.DataFrame:
	return pd.DataFrame(lista, columns=['Nome', 'Idade', 'Sexo', 'Altura', 'Peso'])

In [49]:
dados = [["Maria", 30, "F", 1.65, 65.0], 
         ["João", 25, "M", 1.75, 80.0], 
         ["Ana", 40, "F", 1.70, 70.0], 
         ["Pedro", 20, "M", 1.80, 75.0], 
         ["Lúcia", 35, "F", 1.60, 55.0]]

cria_dataframe(dados)

Nome  Idade Sexo  Altura  Peso
0  Maria     30    F    1.65  65.0
1   João     25    M    1.75  80.0
2    Ana     40    F    1.70  70.0
3  Pedro     20    M    1.80  75.0
4  Lúcia     35    F    1.60  55.0